backend:
  name: git-gateway
  branch: master
media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"
display_url: "https://www.codefordesigners.com/blog/"
slug:
  encoding: "ascii"
  clean_accents: true
collections:
  - name: blog
    label: Blog
    folder: "source/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "html.md"
    format: yaml-frontmatter
    fields:
      - label: Meta Title
        name: meta_title
        widget: string
        required: false
      - label: Meta Description
        name: meta_description
        widget: string
        required: false
      - label: Canonical
        name: canonical
        widget: string
        required: false
      - label: Post Title
        name: title
        widget: string
      - label: Post Summary
        name: summary
        widget: text
      - label: Post Category
        name: category
        widget: select
        options: ["News", "Level Up Fridays", "Tips & Tools", "Design Advice", "Coding Advice"]
      - label: Thumbnail
        name: thumbnail
        widget: image
        required: false
      - label: Author ID
        name: author_id
        widget: select
        options: ["zeke"]
      - label: Published?
        name: published
        widget: boolean
        default: false
      - label: Live Date
        name: live_date
        widget: datetime
      - label: Lead Embed (e.g. video)
        name: lead_embed
        widget: text
      - label: Video?
        name: has_video
        widget: boolean
        default: false
        required: false
      - label: Episode Number
        name: episode_number
        widget: number
        valueType: int
        required: false
        min: 1
      - label: Body
        name: body
        widget: markdown
